# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Create_MSC

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install musescore from apt
        run: sudo apt-get install musescore3 musescore-general-soundfont-small musescore-general-soundfont musescore-general-soundfont-lossless
        
      - name: Test musescore version
        env: 
          QT_QPA_PLATFORM: offscreen
        run: musescore3 -v

      - name: Musescore mp3 creation
        env: 
          QT_QPA_PLATFORM: offscreen
        working-directory: Everybody_Wants_to_Be_a_Cat
        run: musescore3 Everybody_Wants_to_Be_a_Cat.mscz -j job.json

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
 

