# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Create_MSC

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install musescore 3.6
        run: |
          sudo apt-get install musescore
          musescore -v

#      - name: Install musescore 3.6
#        run: |
#          sudo apt-get install -y flatpak
#          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#          sudo flatpak install -y --noninteractive flathub org.musescore.MuseScore  
#          sudo chown 1001:1001 -R /run/user/1001

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
 

